sudo: required
group: deprecated-2017Q3
language: scala
services:
  - docker

notifications:
  email: false
  webhooks:
    urls:
      # travis2slack webhook to enable DMs on openwhisk-team.slack.com to PR authors with TravisCI results
      secure: Yc9ZlTaxhcZT3GWkYyiKpREEORBDLNoTHRqBJNOKvIF1oOCZPH0E9KqaJewwcoSno9G8yhd239kzYtv34moAxYdyKe89SomiH+9wFFpjlS7Ge28+VTWv8yr1EL6pUMW7rJDDODeKxwEHMkdCMARFLrYlQ8xM9quWrc98zqULwusIZpGyVwT3K/4PpWL1OH7D9d0Ain3jods1t7hEzlt8XykLhxpu20bKtxo/0rBJre7f6oCCjEARsHJkvx31VuuZAp5cCLOXPc22Fsd7kqOzzGpsLQICURwUqf7DR8qWyFyXT3QnfJwc2uYXE1yj6SOGxHV1jXOSIymiUFD+8afHlm4SBnqo0UhAIf1z3AJ7r+MSsCTLK7w7kY1WjfOXCK74hiNzS8WmzZJ7C3cVCKYEaxYDDbpUqx9b1+gRaf+acJEuvkMLlkJo5Rze+njdeR9RZbR7i0KR3OCLjXDlu87P2orq6iMNCTDs1FtXlOFeeL42o1YcL1CCKnVXr9feGDSmpZ7Y1ypih+yoeFRYrdG/rPEcgppPXCZBbCWqlzAoRMDrFck+weHTCyMzm16moz2dAxCulm8TrUlb5z4ClbasD6sfdaSFskQtpnW6JtG9gIQt6pfJGkHzMV3Js06sUTNhRWtiLXyUJAftN2xq1skFoMR5beg2a1H9+OKeS03a45E=

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_10110adb91b4_key -iv $encrypted_10110adb91b4_iv -in tests/credentials.json.enc -out tests/credentials.json -d; fi'
  - "./tools/travis/setup.sh"
install: true
script:
  - "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/test.sh"
deploy:
  - provider: script
    script: "./tools/travis/publish.sh ibmfunctions ${TRAVIS_TAG%@*} ${TRAVIS_TAG##*@}"
    on:
      tags: true
      all_branches: true
      repo: ibm-functions/runtime-python
  - provider: script
    script: "./tools/travis/publish.sh ibmfunctions 3.6 master && ./tools/travis/publish.sh ibmfunctions 3.7 master "
    on:
      branch: master
      repo: ibm-functions/runtime-python
  
env:
  global:
  - secure: QTl+38OboTb8QyI6FqOyXEx932GNbEx25dSz4dITvXgItBk4cWhq1MKFy2qmbXlZE4Xt1I8Jqrx4DVv0uuyJJN4tA9B7g8L0Bul87ataL9x8fAM4o3q3OBNxvlQ7R7FesQHeYB6W+v8t89BCHrQgq+YMZCsCHto1Z+BkpZlUryiQJd2oiMICP05GPMk87VSFNVJNeSKhpcOB6A/QfgIWVs6pl+JdB/KbVwL1oEysHwguUfMIWKwhEqFTQRuspTxd6OEEUuxGMoxTuEirj02uZQB/H4xzQcC5DdyjD66XYVAlkar/6eYuLA7DaW4WUxoixc+92PDe9vZC43g2mDXNMF82R50LoOdI8kyP8libKnBhw1BRR7u5zTIVj3Hckqf894K5YGqA3mVhTTxuAjBdcYJBvnNhWstpE3p8fl7qARk1pkyUB6c2CS2JC504gKxqh6HVNOGd9edNo9+N8NKAFhwXNniXkpFcEBa1TmWn0zVBTlBFm5EwtNKVFpyyIlf2DIqUUnCHg2qxL5Kp4wC98syiJCB6PXov7V97p0Y5enwGBTO4CEtgmnK1XcZenWcJvFUETSMNVZ5whDlYgT1atdULo77pHA1QxTaVsX/eyAHgpdQdP5iRSdMZSL6myOhj22UEeziam/iGouqMb7PZg8SSMpLomkjZ/A6caGI8DTQ=
  - secure: ewJfkWCR1AaLB78t1ENt3Z+zfrNJsOE2wpOc26cWDHZyYplZSdGQJqcvLVqWT+ZEPCsevxI6wFdq9Wbv26n1aQhF5uD1kbZwWqVFiKp8SCGGF2zzigDljvQ/5hDeVcytsbqDSEh+ZT4VXUsOgogA6oO1oLoBo2Qig4aj9Teyro9pTeiQmH8/7x+K6CUEm6svb2kbgIPpOffmdjj60LYsGewOjZlenubYm+ti5yUOZ9ruUeDT3CKEDiP2zTlF/TpLU6SRALkDZUNCPTF5lZwHd8yvpEIkH/qddNrqyQUhoiPQJxBQ2XVQLJ+pIv4KQQRIMH8cJ4dR4l1PGX+mj3Eq9AR5zbhzrOd3AsXVmxWkbDGNOGLUWXZKoi17q6U3RapRj0/S5Vc90LOBloJ4lTpH/stZmHKcrWxetodVj2Du5G2PJbAYf0MavnF/NbXYoUfr8EL6gQwbqaWPwKknK6SgDPmrSxOrK3sffGnH2Myv5UdksCokKLbvF32fhR44VF/H7/9RMBHfbWNGAzR6adFN2/T8d4nUpQg3FPnsZzg1uTRC6mCA9M5D7ctjKimjrB/iS1E1DI75GQHcdJaxPm1Zh7XGUrzKepL+caSfvyniNes2cwCwM5HF5OVXgOcu8O4l/3keFHkzxXJSzs7nZ+hnOe7W2GWphs28Y75Z3U+T2yg=
